In [33]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [34]:
#Read the data
data = pd.read_csv("C:\\Users\\user\\Downloads\\news.csv")
#Get shape and head
data.shape
data.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [16]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

In [17]:
cv = CountVectorizer(max_features = 12000)
mat_title = cv.fit_transform(X[:,1]).todense()
mat_title

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
cv_text = CountVectorizer(max_features = 13000)
mat_text = cv.fit_transform(X[:,2]).todense()
mat_text

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
cv_labels = CountVectorizer(max_features = 13000)
mat_labels = cv.fit_transform(Y).todense()
mat_labels

matrix([[1, 0],
        [1, 0],
        [0, 1],
        ...,
        [1, 0],
        [0, 1],
        [0, 1]], dtype=int64)

In [20]:
X_mat = np.hstack((mat_title,mat_text))
X_mat

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X_mat,mat_labels,test_size = 0.2, random_state = 0)

In [22]:
# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train,Y_train)

y_pred=logreg.predict(X_test)

In [28]:
# import the metrics class
CM = metrics.confusion_matrix(Y_test, y_pred)
CM

array([[566,  49],
       [ 50, 602]], dtype=int64)

In [26]:
score=accuracy_score(Y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 92.19%


In [38]:
TP = CM[0][0]
FP = CM[1][0]
TN = CM[1][1]
FN = CM[0][1]

In [39]:
print('Count of news in the test dataset that is predicted correctly as fake :',TP)
print('Count of news in the test dataset that is predicted correctly as real:',TN)

Count of news in the test dataset that is predicted correctly as fake : 566
Count of news in the test dataset that is predicted correctly as real: 602


In [35]:
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Recall value
Recall = TP/(TP+FN)
#F-Score
F_Score = (2*Recall*PPV)/(Recall+PPV)

In [37]:
print('Specificity:',round(TNR,2))
print('Precision:',round(PPV,2))
print('Recall:',round(Recall,2))
print('F-Score:',round(F_Score,2))

Specificity: 0.92
Precision: 0.92
Recall: 0.92
F-Score: 0.92
